// Code generated by codegen from SQL table event
;(function(){

getEventFields = function() {

  return [{
      name: 'event.ID',
      extends: 'lx-input',
      wrapper: 'lx-wrapper-errors',
      defaultOptions: {
        key: 'ID',
        templateOptions: {
          type: 'text',
        }
      }
    },{
      name: 'event.SiteId',
      extends: 'lx-input',
      wrapper: 'lx-wrapper-errors',
      defaultOptions: {
        key: 'SiteId',
        templateOptions: {
          type: 'text',
          label: 'Site ID'
        }
      }
    },{
      name: 'event.Type',
      extends: 'lx-input',
      wrapper: 'lx-wrapper-errors',
      defaultOptions: {
        key: 'Type',
        templateOptions: {
          type: 'text',
          label: 'Event Type',
          disabled: true
        }
      }
    },{
      name: 'event.RefId',
      extends: 'lx-input',
      wrapper: 'lx-wrapper-errors',
      defaultOptions: {
        key: 'RefId',
        templateOptions: {
          type: 'text',
          label: 'Ref ID'
        }
      }
    },{
      name: 'event.Priority',
      extends: 'lx-input',
      wrapper: 'lx-wrapper-errors',
      defaultOptions: {
        key: 'Priority',
        templateOptions: {
          type: 'text',
        }
      }
    },{
      name: 'event.Startdate',
      extends: 'lx-input',
      wrapper: 'lx-wrapper-errors',
      defaultOptions: {
        key: 'StartDate',
        templateOptions: {
          type: 'text',
          label: 'Date Created',
          disabled: true
        }
      }
    },{
      name: 'event.ParentEvent',
      extends: 'lx-input',
      wrapper: 'lx-wrapper-errors',
      defaultOptions: {
        key: 'ParentEvent',
        templateOptions: {
          type: 'text',
          label: 'Parent Event'
        }
      }
    },{
      name: 'event.Username',
      extends: 'lx-input',
      wrapper: 'lx-wrapper-errors',
      defaultOptions: {
        key: 'Username',
        templateOptions: {
          type: 'text',
          label: 'Initially Raised By',
          disabled: true,
        }
      }
    },{
      name: 'event.CreatedBy',
      extends: 'lx-input',
      wrapper: 'lx-wrapper-errors',
      defaultOptions: {
        key: 'CreatedBy',
        templateOptions: {
          type: 'text',
          label: 'Initially Raised By'
        }
      }
    },{
      name: 'event.AllocatedBy',
      extends: 'lx-input',
      wrapper: 'lx-wrapper-errors',
      defaultOptions: {
        key: 'AllocatedBy',
        templateOptions: {
          type: 'text',
          label: 'Allocated By'
        }
      }
    },{
      name: 'event.AllocatedTo',
      extends: 'lx-input',
      wrapper: 'lx-wrapper-errors',
      defaultOptions: {
        key: 'AllocatedTo',
        templateOptions: {
          type: 'text',
          label: 'Allocated To'
        }
      }
    },{
      name: 'event.AllocatedByUser',
      extends: 'lx-input',
      wrapper: 'lx-wrapper-errors',
      defaultOptions: {
        key: 'AllocatedByUser',
        templateOptions: {
          type: 'text',
          label: 'Allocated By',
          disabled: true
        }
      }
    },{
      name: 'event.AllocatedToUser',
      extends: 'lx-input',
      wrapper: 'lx-wrapper-errors',
      defaultOptions: {
        key: 'AllocatedToUser',
        templateOptions: {
          type: 'text',
          label: 'Allocated To',
          disabled: true
        }
      }
    },{
      name: 'event.Completed',
      extends: 'lx-input',
      wrapper: 'lx-wrapper-errors',
      defaultOptions: {
        key: 'Completed',
        templateOptions: {
          type: 'text',
          label: 'Date Completed',
          disabled: true
        }
      }
    },{
      name: 'event.LabourCost',
      extends: 'lx-input',
      wrapper: 'lx-wrapper-errors',
      defaultOptions: {
        key: 'LabourCost',
        templateOptions: {
          type: 'text',
          label: 'Labour Cost',
          disabled: true
        }
      }
    },{
      name: 'event.MaterialCost',
      extends: 'lx-input',
      wrapper: 'lx-wrapper-errors',
      defaultOptions: {
        key: 'MaterialCost',
        templateOptions: {
          type: 'text',
          label: 'Material Cost',
          disabled: true
        }
      }
    },{
      name: 'event.OtherCost',
      extends: 'lx-input',
      wrapper: 'lx-wrapper-errors',
      defaultOptions: {
        key: 'OtherCost',
        templateOptions: {
          type: 'text',
          label: 'Other Cost',
          disabled: true
        }
      }
    },{
      name: 'event.Notes',
      extends: 'lx-input',
      wrapper: 'lx-wrapper-errors',
      defaultOptions: {
        key: 'Notes',
        templateOptions: {
          type: 'text',
          label: 'Notes'
        }
      }
    },{
      name: 'event.Status',
      extends: 'lx-input',
      wrapper: 'lx-wrapper-errors',
      defaultOptions: {
        key: 'Status',
        templateOptions: {
          type: 'text',
          label: 'Status',
          disabled: true          
        }
      }
  }] // end fields

} // getEventFields

getEventForm = function() {

  return [{
    type: 'lx-flex',
    templateOptions: {
      flex: { container: "row", item: "6"},
      fields: [
        {type: 'event.Type'},
      ]
    }
  },{
    type: 'lx-flex',
    templateOptions: {
      flex: { container: "row", item: "6"},
      fields: [
        {type: 'event.Startdate'},
        {type: 'event.Completed'},
      ]
    }
  },{
    type: 'lx-flex',
    templateOptions: {
      flex: { container: "row", item: "4"},
      fields: [
        {type: 'event.Username'},
        {type: 'event.AllocatedByUser'},
        {type: 'event.AllocatedToUser'},
      ]
    }
  },{
    type: 'lx-flex',
    templateOptions: {
      flex: { container: "row", item: "4"},
      fields: [
        {type: 'event.LabourCost'},
        {type: 'event.MaterialCost'},
        {type: 'event.OtherCost'},
      ]
    }
  },{
    type: 'lx-flex',
    templateOptions: {
      flex: { container: "row", item: "12"},
      fields: [
        {type: 'event.Status'},
      ]
    }

  }]
} // getEventForm

})();
